services:
  #1. task api
  api:
    build: .
    ports:
      - "3000:3000"
      - "51212:51212" # Add this for Prisma Studio
    environment:
      - DATABASE_URL=postgresql://postgres:61289@db:5432/task_db
      - JWT_SECRET={JWT_SECRET}
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN} # <--- Add this
      - SPLUNK_URL=${SPLUNK_URL}             #
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      # Use these exact flags to bypass the license gate
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=Payx2026! # Use a strong password in production
      # SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN} # Replace with your desired HEC token
      # SPLUNK_URL=${SPLUNK_URL}
    ports:
      - "8000:8000"  # Splunk Web Interface
      - "8088:8088"  # HEC Port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
  #2. Postgres DB
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 61289
      POSTGRES_DB: task_db
    ports:
      - "5423:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: