services:
  #1. task api
  api:
    build: .
    ports:
      - "3000:3000"
      - "51212:51212" # Add this for Prisma Studio
    environment:
      - DATABASE_URL=postgresql://postgres:61289@db:5432/task_db
      - JWT_SECRET={JWT_SECRET}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme # Use a strong password in production
      - SPLUNK_HEC_TOKEN=your_hec_token_here # Replace with your desired HEC token
    ports:
      - "8000:8000"  # Splunk Web Interface
      - "8088:8088"  # HEC Port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
  #2. Postgres DB
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 61289
      POSTGRES_DB: task_db
    ports:
      - "5423:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: