# Should integration tests run against real database?
# NO. It should run against a transient test environment
#     Like, in GitHub actions, we can spin up a temporary Postgres container
#     and run tests against that containerized database instance.

name: Task API CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 61289
          POSTGRES_DB: task_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d task_db_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Run Primsa Migrations
      run: npx prisma migrate deploy
      env:
        DATABASE_URL: postgresql://postgres:61289@localhost:5432/task_db_test
    - name: Run Prisma Client Generation
      run: npx prisma generate

    - name: Sync Database Schema
      # We use db push here because it's a transient DB and 
      # it ensures the AuditLog table is created even if no migration file exists yet.
      run: npx prisma db push --accept-data-loss
      env:
        DATABASE_URL: postgresql://postgres:61289@localhost:5432/task_db_test

    - name: Run Integration Tests
      run: npm run test:ci
      env:
        DATABASE_URL: postgresql://postgres:61289@localhost:5432/task_db_test
        JWT_SECRET: ${{ secrets.JWT_SECRET || 'test_secret_for_ci'}} # why set it up for test? Environment parity and security posture. Rotates secret key and complies SOC2 guidelines
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}